#!/bin/bash

# --------------------- CONFIG BEGIN ---------------------

# The location of the saves folder on your cloud storage.
destinationFolder=/Games/Batocera/saves

# Waiting time between two backups in seconds. The below configuration means that the service will do a backup every minute.
waitSeconds=10

# ---------------------- CONFIG END ----------------------

PIDFile=/var/run/backup.pid

do_sync() {
    rclone sync /userdata/saves backup:${destinationFolder} -P

    # TODO: Make is possible to sync other stuff.
    # Examples:
    #     /userdata/system/batocera.conf
    #     /userdata/bios
    #     /userdata/roms
}

case "$1" in
    manual)
        do_sync
        ;;
    start)
        echo $BASHPID >>${PIDFile}
        while true; do
            do_sync
            sleep ${waitSeconds}
        done
        ;;
    stop)
        kill $(cat ${PIDFile})
        rm ${PIDFile}
        ;;
    status)
        echo "STUB: backup status"
        ;;
esac
