#!/bin/bash

# --------------------- CONFIG BEGIN ---------------------
# The saves folder on your cloud storage.
destinationFolder=/Games/Batocera/saves
# ---------------------- CONFIG END ----------------------

do_sync() {
    # TODO: Improve output.
    # TODO: Consider making it async: https://rclone.org/rc/#running-asynchronous-jobs-with-async-true
    rclone rc sync/sync srcFs=/userdata/saves dstFs=backup:${destinationFolder} -P

    # TODO: Make is possible to sync other stuff.
    # Examples:
    #     /userdata/system/batocera.conf
    #     /userdata/bios
    #     /userdata/roms
}

case "$1" in
    manual)
        do_sync
        ;;
    start)
        nohup rclone rcd --rc-no-auth &>/dev/null &
        ;;
    stop)
        rclone rc core/quit &>/dev/null
        ;;
    status)
        # TODO: Improve output.
        rclone rc core/stats
        ;;
esac
